(test
 (name test_model)
 (modules test_model)
 (libraries scrubline_model))

(test
 (name test_correspondence)
 (modules test_correspondence)
 (libraries scrubline_model))

(test
 (name test_reader)
 (modules test_reader)
 (libraries scrubline))

(test
 (name test_utf8)
 (modules test_utf8)
 (libraries scrubline))

(test
 (name test_msgpack)
 (modules test_msgpack)
 (libraries scrubline))

(test
 (name test_encode)
 (modules test_encode)
 (libraries scrubline))
